---
version: "3.6"
services:
  backend:
    image: reviewsys/backend:latest
    # image: golang:alpine
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./config.json:/bin/config.json
      # - ./:/go/src/github.com/reviewsys/backend
    container_name: backend

  db:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: reviewsys
    ports:
      - 5432:5432
    container_name: db
