---
version: "3.6"
services:
  backend:
    image: reviewsys/backend:latest
    build:
      context: ./
    ports:
      - 8080:8080
    volumes:
      - ./config.json:/config.json
    container_name: backend

  db:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: reviewsys
    container_name: db
