// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/delivery/grpc/user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TeamId               int64                `protobuf:"varint,4,opt,name=TeamId,proto3" json:"TeamId,omitempty"`
	Name                 string               `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	IsAdmin              bool                 `protobuf:"varint,6,opt,name=IsAdmin,proto3" json:"IsAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type CreateUserRequest struct {
	Payload              *User    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetPayload() *User {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadUserRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{3}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

func (m *ReadUserRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{4}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateUserRequest struct {
	Payload              *User                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	GerogeriGegege       *field_mask.FieldMask `protobuf:"bytes,2,opt,name=gerogeri_gegege,json=gerogeriGegege,proto3" json:"gerogeri_gegege,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetPayload() *User {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateUserRequest) GetGerogeriGegege() *field_mask.FieldMask {
	if m != nil {
		return m.GerogeriGegege
	}
	return nil
}

type UpdateUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{6}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteUserRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{7}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{8}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type ListUserRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{9}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

func (m *ListUserRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListUserRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListUserRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListUserRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListUserResponse struct {
	Results              []*User         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	PageInfo             *query.PageInfo `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListUserResponse) Reset()         { *m = ListUserResponse{} }
func (m *ListUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserResponse) ProtoMessage()    {}
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31cef1674bc06c59, []int{10}
}

func (m *ListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponse.Unmarshal(m, b)
}
func (m *ListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponse.Marshal(b, m, deterministic)
}
func (m *ListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponse.Merge(m, src)
}
func (m *ListUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserResponse.Size(m)
}
func (m *ListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponse proto.InternalMessageInfo

func (m *ListUserResponse) GetResults() []*User {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListUserResponse) GetPageInfo() *query.PageInfo {
	if m != nil {
		return m.PageInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.CreateUserResponse")
	proto.RegisterType((*ReadUserRequest)(nil), "user.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "user.ReadUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "user.DeleteUserResponse")
	proto.RegisterType((*ListUserRequest)(nil), "user.ListUserRequest")
	proto.RegisterType((*ListUserResponse)(nil), "user.ListUserResponse")
}

func init() { proto.RegisterFile("app/delivery/grpc/user/user.proto", fileDescriptor_31cef1674bc06c59) }

var fileDescriptor_31cef1674bc06c59 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xae, 0x1c, 0x4f, 0x76, 0x4e, 0x80, 0xa6, 0x21, 0x96, 0x54, 0x36, 0x06, 0xcc, 0x13, 0x3a,
	0xc0, 0x37, 0x96, 0x8a, 0x74, 0x3f, 0xa9, 0x87, 0x5e, 0x24, 0xdd, 0x5a, 0x78, 0xd8, 0x86, 0x41,
	0x69, 0x6f, 0x76, 0x63, 0xd0, 0xd2, 0xb1, 0x46, 0x58, 0x12, 0x59, 0x92, 0xca, 0xe6, 0x9b, 0xdd,
	0xec, 0xa9, 0xec, 0x87, 0xd8, 0x13, 0xec, 0x61, 0x0a, 0x4a, 0x54, 0xeb, 0xd8, 0x29, 0x92, 0xc0,
	0x80, 0x40, 0xea, 0x9c, 0xef, 0x7c, 0x87, 0x1f, 0xbf, 0x23, 0xc3, 0x57, 0x54, 0x88, 0x30, 0xc1,
	0x8c, 0x5d, 0xa1, 0x5c, 0x86, 0xa9, 0x14, 0x71, 0x58, 0x2a, 0x94, 0xd5, 0x23, 0x10, 0x92, 0x6b,
	0x4e, 0xda, 0x66, 0xdd, 0xff, 0x32, 0xe5, 0x3c, 0xcd, 0x30, 0xac, 0xde, 0xcd, 0xca, 0x79, 0xa8,
	0x59, 0x8e, 0x4a, 0xd3, 0x5c, 0xd4, 0x69, 0xfd, 0x71, 0xca, 0xf4, 0x9f, 0xe5, 0x2c, 0x88, 0x79,
	0x1e, 0xb2, 0x62, 0xce, 0x67, 0x19, 0xff, 0x9b, 0x0b, 0x2c, 0x6a, 0x44, 0x3c, 0x4a, 0xb1, 0x18,
	0xa5, 0x5c, 0xe6, 0x21, 0x17, 0x9a, 0xf1, 0x42, 0x85, 0x66, 0x63, 0xb1, 0x3f, 0x7d, 0x0a, 0x4b,
	0x75, 0x46, 0xd5, 0x88, 0x0a, 0x31, 0xd2, 0x9c, 0x67, 0x0b, 0xa6, 0x43, 0xd3, 0xa1, 0x44, 0xc5,
	0x4b, 0x19, 0xe3, 0x87, 0x85, 0x2d, 0x33, 0xd8, 0xee, 0x71, 0xce, 0x30, 0x4b, 0xa6, 0x39, 0x55,
	0x0b, 0x9b, 0xf1, 0xf3, 0xdd, 0x89, 0xde, 0x95, 0x46, 0x91, 0x98, 0x67, 0x19, 0xc6, 0xa6, 0xe1,
	0x29, 0x17, 0x28, 0xa9, 0xe6, 0x52, 0xd5, 0xb5, 0xfc, 0x7f, 0x5b, 0xd0, 0x7e, 0xab, 0x50, 0x92,
	0x6f, 0xa1, 0xc5, 0x12, 0xcf, 0x19, 0x38, 0xc3, 0x83, 0xd3, 0xe3, 0xa0, 0xaa, 0x14, 0x48, 0x11,
	0x07, 0x93, 0x04, 0x0b, 0xcd, 0xe6, 0x0c, 0xe5, 0xc5, 0xc3, 0xf5, 0xaa, 0x07, 0xd0, 0x25, 0xed,
	0xb2, 0x64, 0xc9, 0xd0, 0x89, 0x5a, 0x2c, 0x21, 0xcf, 0x01, 0x62, 0x89, 0x54, 0x63, 0x32, 0xa5,
	0xda, 0x6b, 0x55, 0xf0, 0x7e, 0x50, 0x1f, 0x21, 0x68, 0x8e, 0x10, 0xbc, 0x69, 0x64, 0x8e, 0xf6,
	0x6d, 0xf6, 0xb9, 0x36, 0xd0, 0x52, 0x24, 0x0d, 0x74, 0xef, 0x76, 0xa8, 0xcd, 0x3e, 0xd7, 0xe4,
	0x04, 0xdc, 0x37, 0x48, 0xf3, 0x49, 0xe2, 0xb5, 0x07, 0xce, 0x70, 0x2f, 0xb2, 0x3b, 0x42, 0xa0,
	0xfd, 0x1b, 0xcd, 0xd1, 0xfb, 0x6c, 0xe0, 0x0c, 0xf7, 0xa3, 0x6a, 0x4d, 0x3c, 0xe8, 0x4c, 0xd4,
	0x79, 0x92, 0xb3, 0xc2, 0x73, 0x07, 0xce, 0xb0, 0x1b, 0x35, 0xdb, 0x71, 0x77, 0xbd, 0xea, 0xb5,
	0xbb, 0xce, 0xc0, 0xf1, 0x9f, 0xc3, 0xd1, 0xcb, 0xaa, 0x2f, 0x23, 0x45, 0x84, 0xef, 0x4a, 0x54,
	0x9a, 0x3c, 0x81, 0x8e, 0xa0, 0xcb, 0x8c, 0xd3, 0x46, 0x16, 0x08, 0x2a, 0x43, 0x55, 0x39, 0x4d,
	0xc8, 0x3f, 0x03, 0xb2, 0x09, 0x55, 0x82, 0x17, 0x0a, 0x89, 0x0f, 0xae, 0x44, 0x55, 0x66, 0xfa,
	0x06, 0xa8, 0x8d, 0xf8, 0x67, 0x70, 0x18, 0x21, 0x4d, 0x36, 0x29, 0xbf, 0xbe, 0xf5, 0x12, 0x8c,
	0xe8, 0xfe, 0x77, 0xf0, 0xe8, 0x23, 0xf2, 0x1e, 0x8c, 0xff, 0xc0, 0xd1, 0xdb, 0x4a, 0xc3, 0x7b,
	0x1f, 0x93, 0xbc, 0x84, 0xc3, 0x14, 0x25, 0x4f, 0x51, 0xb2, 0x69, 0x8a, 0xe6, 0xf7, 0xc9, 0xcb,
	0x7e, 0x65, 0xfc, 0xfa, 0x2b, 0x55, 0x8b, 0xe8, 0x61, 0x03, 0x79, 0x5d, 0x21, 0x8c, 0x56, 0x9b,
	0xfc, 0xf7, 0xe8, 0x7c, 0x0c, 0x47, 0x3f, 0x62, 0x86, 0xd7, 0x3b, 0xbf, 0xa3, 0x5a, 0x9f, 0x03,
	0xd9, 0xc4, 0xd6, 0xac, 0xfe, 0xff, 0x0e, 0x1c, 0xfe, 0xc2, 0x94, 0xde, 0x2c, 0x18, 0x82, 0x3b,
	0x67, 0x99, 0x46, 0x69, 0x8b, 0x3e, 0x0e, 0x9a, 0xf1, 0x0a, 0xa8, 0x60, 0xc1, 0xab, 0x2a, 0xc6,
	0x8a, 0x34, 0xb2, 0x69, 0xe4, 0x29, 0x74, 0xb9, 0x4c, 0x50, 0x4e, 0x67, 0x4b, 0x2b, 0xc7, 0xf1,
	0x75, 0xc8, 0x25, 0x97, 0xda, 0x00, 0x3a, 0x55, 0xda, 0xc5, 0x92, 0x7c, 0x63, 0x28, 0x30, 0x4b,
	0x94, 0x35, 0xfc, 0x17, 0xdb, 0x14, 0x98, 0x25, 0x97, 0x68, 0xa7, 0x35, 0xb2, 0xb9, 0xe4, 0x29,
	0xb8, 0x82, 0xa6, 0xac, 0x48, 0x2b, 0xbf, 0x1f, 0x9c, 0x7a, 0xd7, 0x51, 0xbf, 0x9b, 0x18, 0xad,
	0x11, 0x75, 0x9e, 0x9f, 0xc3, 0xa3, 0x8f, 0xa7, 0xb3, 0x42, 0x3f, 0x81, 0x4e, 0x2d, 0xa7, 0xf2,
	0x9c, 0xc1, 0xde, 0xf6, 0x4d, 0xdb, 0x10, 0x79, 0x06, 0xfb, 0x82, 0xa6, 0x38, 0x35, 0x0c, 0xf6,
	0x50, 0x27, 0x3b, 0x74, 0x38, 0x29, 0xe6, 0x3c, 0xea, 0x0a, 0xbb, 0x3a, 0xfd, 0xaf, 0x05, 0x07,
	0xa6, 0xcc, 0x25, 0xca, 0x2b, 0x16, 0x23, 0x79, 0x01, 0x6e, 0x3d, 0x15, 0xe4, 0x71, 0xcd, 0xb1,
	0x33, 0x5e, 0x7d, 0x6f, 0x37, 0x60, 0xaf, 0xe6, 0x01, 0xf9, 0x1e, 0xda, 0xc6, 0xe0, 0xe4, 0xb8,
	0xce, 0xd9, 0x1a, 0x93, 0xfe, 0xc9, 0xf6, 0xeb, 0x0f, 0xc0, 0x17, 0xe0, 0xd6, 0x0e, 0x6b, 0x78,
	0x77, 0xfc, 0xde, 0xf0, 0xee, 0x1a, 0xb1, 0xe6, 0x35, 0xaa, 0x35, 0xbc, 0x5b, 0xfe, 0x68, 0x78,
	0xb7, 0x85, 0xf5, 0x1f, 0x90, 0xd7, 0xe0, 0xd6, 0x1e, 0x6b, 0x78, 0x77, 0xdc, 0xda, 0xf0, 0xde,
	0x60, 0x45, 0x58, 0xaf, 0x7a, 0x6e, 0xfd, 0x19, 0xee, 0xbb, 0xeb, 0x55, 0xaf, 0xd5, 0x75, 0x2e,
	0xc6, 0x7f, 0x9c, 0x6d, 0x7c, 0xe5, 0x25, 0x5e, 0x31, 0xfc, 0x4b, 0x2d, 0x55, 0x38, 0xa3, 0xf1,
	0x02, 0x8b, 0x24, 0xbc, 0xf9, 0x1f, 0xef, 0x07, 0xf3, 0x98, 0xb9, 0xd5, 0x28, 0x3e, 0x7b, 0x1f,
	0x00, 0x00, 0xff, 0xff, 0x72, 0x23, 0x1e, 0x73, 0x17, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Read(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	List(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
	Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Read(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error) {
	out := new(ReadUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) List(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Read(context.Context, *ReadUserRequest) (*ReadUserResponse, error)
	Update(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	List(context.Context, *ListUserRequest) (*ListUserResponse, error)
	Delete(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Read(ctx, req.(*ReadUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).List(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _UserService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/delivery/grpc/user/user.proto",
}
